### ISSUE TITLE
UnionFind

### ISSUE THREAD

**Issue by nishiyamayo** [CyberAgent/proconlib4ca#8]
# 概要
UnionFindのドキュメントと解説資料を用意する

# やること
- [x] ドキュメント: `./doc/union_find.md`
- [x] 解説資料

**Comment by RyochanUedasan** [comment]
- ドキュメント: ./doc/union_find.md
  - https://github.com/CyberAgent/proconlib4ca/tree/feature/union_find

- 解説資料
  - https://esa-pages.io/p/sharing/2934/posts/4069/06a75966fb96d3ae71d5.html
